# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: autofix.ci
run-name: 'autofix.ci "${{ github.event.pull_request.title || github.event.head_commit.message || github.event_name }}" by @${{ github.actor }}'
on:
  push: { branches: ["master"] }
  pull_request:
  workflow_call:
  workflow_dispatch:
permissions: { contents: write }
jobs:
  autofix:
    name: Format and autofix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: kjanat/runner@master
      - uses: oven-sh/setup-bun@v2
      - run: runner install fmt:autofix
      - if: github.ref_name == 'master' && github.event_name == 'push'
        run: run fmt:cfg:up
      - if: github.ref_name == 'master' && github.event_name == 'push'
        run: |
          git ls-remote "https://github.com/kjanat/kjanat.git" HEAD | awk '{print substr($1, 1, 8)}' \
          | xargs -r -I{} sed -i -E 's#(github\.com/kjanat/kjanat/raw/)[0-9a-zA-Z]{4,40}(/configs/dprint\.remote\.json)#\1{}\2#g' \
            .dprint.jsonc
      - uses: autofix-ci/action@v1
